language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
env:
  - SYMFONY_CONSOLE_VERSION=2.8.*
  - SYMFONY_CONSOLE_VERSION=3.*
matrix:
  include:
    - php: 7.1
      env: SYMFONY_CONSOLE_VERSION=4.*
    - php: 7.2
      env: SYMFONY_CONSOLE_VERSION=4.*

services:
  - rabbitmq

addons:
  hosts:
    - default

install:
  - composer require symfony/console:${SYMFONY_CONSOLE_VERSION}
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --config=phpunit-coverage.xml --coverage-clover=coverage.xml
  - vendor/bin/phpunit --config=phpunit-validation.xml
  - vendor/bin/phpcs --standard=PSR2 src

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
