language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - rabbitmq

addons:
  hosts:
    - default

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
