version: '3'

services:
    rabbitmq:
        build: rabbitmq
        ports:
            - "15682:15672"

    php-amqp-php-lib:
        build: php-amqp-php-lib
        volumes:
            - ../:/app
        working_dir: /app
        depends_on:
            - rabbitmq

    php-pecl-ext:
        build: php-pecl-ext
        volumes:
            - ../:/app
        working_dir: /app
        depends_on:
            - rabbitmq

    php:
        build: php
        volumes:
            - ../:/app
        depends_on:
          - rabbitmq